#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Pratisamvid '
  rel-author: ''
  rel-publisher: ''

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # Pratisamvid

  Pratisamvid is India's first R&D data analytics and AI startup focused on providing Analytics solutions for Indian clients.
  We do predictive modeling for Customer, Retail, CPG and Marketing industries.
  

contact: >
  # Contact

  You may contact me [through my email](mailto:anaghakaranam@gmail.com) if you have any questions or would like to bring up any issues.

#-------------------------------
# Work Section

projects:
- {name: 'Do Binge Watchers order food online? The problem of Program Evaluation', folder: 'proj-1', file: 'projects/Program_Evaluation.html'}
- {name: 'Solving Lead Generation problem & The Lean Analytics Cycle', folder: 'proj-2', file: 'projects/Lead_Generation.html'}
#- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
#- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
#- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: '#'}
- {icon: 'instagram', link: '#'}
- {icon: 'github', link: '#'}
- {icon: 'linkedin', link: '#'}
- {icon: 'envelope', link: 'mailto:#'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
